{% set name = "ftd2xx" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf97c03048d56686e4f05f8931f68fb05a6de01cf9a571e404fbb57e957271b4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - m2-patch  # [win]
  host:
    - python
    - pip
  run:
    - python
    - future
    - pywin32  # [win]

# Tests done in run_test.py

about:
  home: https://github.com/snmishra/ftd2xx/blob/master/LICENSE
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ftd2xx is a simple python wrapper around the D2XX DLL from FTDI using ctypes.

  description: |
    The API based on Pablo Bleyer Kocik’s d2xx extension.

    Version 1.1.0 is compatible with Python 3. Please ensure you have FTDI
    drivers installed or available where the linker looks for shared libraries
    (e.g., PATH on windows, LD_LIBRARY_PATH or standard library directories
    on Linux)

extra:
  recipe-maintainers:
    - hmaarrfk
