travis:
  secure:
    BINSTAR_TOKEN: FAdvEBjOF/4OuqN3rXvEnxQgoh0qaB8oRUlKhpCa6rszFEQFswVS1WiG7EPjYHtsaTbcNG+39dBMLCwqg+FLky7DONuv30m7fHa+5FrU3MhnDYsahI3ZF80EXg35QA26zNVLIwCkx9lmY1qIJoYiqdIkspKN2IEveKc12JzeLT7fAlKiZ9nZ1xifPIPbLhoO7VaMIj/V+QXSJ7GIK/gpRxT9kaNVU8Zs3jggEEB1n1zHVMbQnhTJwfb576J2KAtUF8jfqy4H74xJpihK3Mbt9+eCJ/sHTwsS6jgR90e6msFtkjRFuBsjHHFadc+YdzM1LU+w53wLzQ9UzffvTTAcaj7k0eSqqupDR+CCQY3mYTmceyE4YIbIfMwtvAdtzoZqZVpy/ixRrA+SfGSkBB99hdhHpwhb+DIUSRzPuZjHpO5qZ/7KoVA0uBrAHXAwl1DOmMSMPqgXEXR6LHVZUuw39+ewPVa0BqAY+wGWBsVvS7zmdXJF/+T4CnlSV7+DAKMWeoM5OHG0bXDgFpvqSOTGDQWycGJcw0NQ3K++6kR27b1AG/k3Bab1QxLLCQzvzNeaP5MXNfi/1tscKDwey28yfjDN17s8mEyBQ2a+zXMAc2MsPo+jjVjM7u7NsrFAhoKZ+iGlt90IbZa9muvrcCoVN2Zmind2KOQRplntW9a8p8E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
